feat: adds recently searched journeys to location search and ability to clear history. Closes #673
AtB-AS/mittatb-app pull request #1004
Opened 2021-03-17 21:51 UTC by mikaelbr

Closes #673

This PR adds the ability to re-use previous journey searches. Currently not implemented with filtering. Meaning previous journey searches will not show if matching the current query. This can be added at a later point or now if this is valued as important.

With this, I also added the ability to clear search history as a part of privacy. I feel this is more important now with actual journey searches, even though it is still only stored locally. (I also needed it for testing).

### Example screen shots

<img width="513" alt="Screenshot 2021-03-17 at 22 47 10" src="https://user-images.githubusercontent.com/606374/111543258-164bfe80-8773-11eb-94d3-ae7401bef43e.png">
<img width="510" alt="Screenshot 2021-03-17 at 22 47 06" src="https://user-images.githubusercontent.com/606374/111543262-1815c200-8773-11eb-8be9-cacf148c22f3.png">t of
<img width="539" alt="Screenshot 2021-03-17 at 22 46 46" src="https://user-images.githubusercontent.com/606374/111543263-18ae5880-8773-11eb-880d-454111a1d112.png">

2021-03-18 08:56 UTC, mikaelbr commented
Limits the current latest journey suggestions to 3 for now. Do we think this needs to be configurable through remote config so we can update that on the fly? cc @pettersuul @hildeor

2021-03-19 07:33 UTC, gorandalum commented
Nice. I'll take a look at this now.

Would it make sense to have these "Most recent journeys" on the Assistant screen also? I feel they kinda belong there more than the favourite places which are there now.

<img width="595" alt="Screenshot 2021-03-19 at 08 25 36" src="https://user-images.githubusercontent.com/675421/111745982-aaaa8400-888d-11eb-8d6c-903ff9adeecc.png">

2021-03-19 09:07 UTC, gorandalum requested changes
Great, this will be a nice new functionality for the users.

I feel that the code is kind of hard to follow, but maybe it is no way around it when we give LocationSearch this added functionality. One other hint that the code is complex is that it all looked ok when reviewing, but when testing I found one or more bugs (I don't know if it is the same one).

Bug 1:
I first selected a recent journey between Kvennhusveien 8 (My position) and Ila. After that I tried changing the from-location, but after selecting Solsiden the from-location was still Kvennhusveien 8:
<img width="400" src="https://user-images.githubusercontent.com/675421/111755935-f19e7680-8899-11eb-9ad6-287ee1a35ff5.gif">

Bug 2:
I first selected a recent journey between Ila and Solsiden. After that I changed the to-location to Hallset, and then the from-location was unintentionally changed to my position (Kvennhusveien 8):
<img width="400" src="https://user-images.githubusercontent.com/675421/111756382-6e315500-889a-11eb-9681-3f74d526f673.gif">

2021-03-22 20:20 UTC, mikaelbr commented
@gorandalum Simplified logic now and seems to fix the issue also. Check if the logic is easier to follow now.

2021-03-23 09:01 UTC, gorandalum commented
LGTM! :+1:
And no insects found when testing.

2021-03-23 09:01 UTC, gorandalum approved these changes

2021-03-23 09:09 UTC, merged