feat: New sign-in focused onboarding
AtB-AS/mittatb-app pull request #1157
Opened 2021-05-19 12:43 UTC by gorandalum

Onboarding updated to the latest design. The new onboarding dialog is
more focused on getting the user to sign in.

2021-05-19 13:09 UTC, gorandalum commented
<div>
<img width="400" alt="Screenshot 2021-05-19 at 14 44 08" src="https://user-images.githubusercontent.com/675421/118817970-17ed8c00-b8b4-11eb-8593-21052c2c7ab2.png">
<img width="400" alt="Screenshot 2021-05-19 at 14 44 11" src="https://user-images.githubusercontent.com/675421/118817985-1cb24000-b8b4-11eb-8d01-e076a4c74c66.png">
<img width="400" alt="Screenshot 2021-05-19 at 14 48 16" src="https://user-images.githubusercontent.com/675421/118817976-1ae87c80-b8b4-11eb-85f5-9aa16e418ffa.png">
<img width="400" alt="Screenshot 2021-05-19 at 14 44 14" src="https://user-images.githubusercontent.com/675421/118817980-1b811300-b8b4-11eb-8f1b-593414465817.png">
</div>

2021-05-25 14:27 UTC, gorandalum commented
Etter den nyeste vendingen så er innlogging-fokusert onboarding satt på vent. Det er da implementert en onboarding i den nye stilen, men uten login-fokus.

Figma: https://www.figma.com/file/WsvD8b5PnUwvvRJiyRe6I9/?node-id=5222%3A21656

Skjermbilder fra app:
<div>
<img width="400" alt="Screenshot 2021-05-25 at 16 23 22" src="https://user-images.githubusercontent.com/675421/119514762-94c9ab80-bd75-11eb-9648-cbab1f0d760b.png">
<img width="400" alt="Screenshot 2021-05-25 at 16 21 27" src="https://user-images.githubusercontent.com/675421/119514747-92675180-bd75-11eb-8925-ea4daac51c0b.png">
</div>

2021-05-26 08:23 UTC, monopoint requested changes

2021-05-26 08:23 UTC, monopoint commented on src/screens/Onboarding/index.tsx
> +      {/*) : (*/}
Dette burde vel fjernes

2021-05-27 09:04 UTC, gorandalum commented on src/screens/Onboarding/index.tsx
> +      {/*) : (*/}
Jeg er ikke så glad i å ha utkommentert kode liggende, men føler dette er rett rundt hjørnet av funksjonalitet vi skal ha. Hvis vi fjerner koden så eksisterer det komponenter som "PhoneInputInOnboarding" og "ConfirmCodeInOnboarding"  uten noen referanser til hvordan de er tenkt brukes. Og det å fjerne selve komponentene tror jeg ikke er hensiktsmessig da det ble brukt litt tid til å utvikle, før innlogging ble tatt ut av scope i siste liten.

2021-05-27 09:16 UTC, merged

2021-05-30 07:11 UTC, tormoseng commented
Testet OK i staging på iOS pg Android