fix: accessibility for favorites and page title focus on scale transitions
AtB-AS/mittatb-app pull request #1253
Opened 2021-06-11 08:19 UTC by monopoint

fixes #1192, fixes #1191, fixes #1189

2021-06-14 11:11 UTC, gorandalum requested changes
Ser bra ut! Jeg velger "Request changes" slik at jeg får høre om endring til 200ms i use-focus-on-load var tiltenkt å være med. Hvis den skal være med så må jeg teste litt grundigere hvilken effekt det har rundt omkring på iPhone.

2021-06-14 11:11 UTC, gorandalum commented on src/screens/Profile/FavoriteList/SortableListFallback.tsx
> +    opacity: 0.2,
Kunne vurdert og i stedet brukt `colorType="disabled"` på `ThemeIcon`, da hadde man fått opacity knyttet opp mot hva som er definert i design-systemet.

2021-06-14 11:11 UTC, gorandalum commented on src/screens/Profile/FavoriteList/SortFavorites.tsx
> +        leftButton={{type: 'cancel'}}
Bra! Ser det er flere steder det er brukt "Lukk" hvor det bør være "Avbryt".

2021-06-14 18:54 UTC, monopoint commented on src/utils/use-focus-on-load.ts
> +        setTimeout(() => giveFocus(setFocusOnLoad, focusRef), 200);
Ja, den fikser at fokus ikke settes på på sider som har scale trasitions

2021-06-14 18:58 UTC, monopoint commented on src/utils/use-focus-on-load.ts
> +        setTimeout(() => giveFocus(setFocusOnLoad, focusRef), 200);
#1189

2021-06-16 06:47 UTC, monopoint commented on src/screens/Profile/FavoriteList/SortableListFallback.tsx
> +    opacity: 0.2,
bra! endret

2021-06-16 06:56 UTC, gorandalum approved these changes

2021-06-16 13:08 UTC, merged