feat: Add saving of previously used card
AtB-AS/mittatb-app pull request #1523
Opened 2021-08-27 13:36 UTC by brorhb

resolves #1497

![Simulator Screen Shot - iPhone 11 - 2021-09-01 at 11 02 41](https://user-images.githubusercontent.com/12571304/131643724-786a6c52-a0b4-4ae4-830c-136186e67769.png)

![Simulator Screen Shot - iPhone 11 - 2021-09-01 at 11 02 54](https://user-images.githubusercontent.com/12571304/131643715-29337fe0-44a1-4d1d-b135-c396e5a547b7.png)

![Simulator Screen Shot - iPhone 11 - 2021-09-01 at 11 02 49](https://user-images.githubusercontent.com/12571304/131643720-90e15f68-965b-48a3-9cf1-ab552441ee10.png)

2021-09-01 12:00 UTC, cbrevik reviewed
Et par kommentarer, skal gå mer nøye igjennom senere

2021-09-01 12:00 UTC, cbrevik commented on src/assets/svg/icons/actions/Confirm.tsx
> +function SvgConfirm(props: SvgProps, fill?: string) {
SVG-er bør ikke endres direkte, vi bruker et script til å gjøre dette. Vi legger ikoner under `<root>/assets/svgs`, og så kjører vi `yarn generate-svgs` for å generere alle React-componentene for disse. Gjerne ta kontakt om uklart :D

2021-09-01 12:39 UTC, cbrevik commented on src/assets/svg/icons/actions/Confirm.tsx
> +function SvgConfirm(props: SvgProps, fill?: string) {
Hvis du må endre fill så skal det være mulig å gjøre dette fra utsiden av denne componenten

2021-09-01 12:43 UTC, cbrevik commented on src/screens/Ticketing/Purchase/Payment/SelectCreditCard/index.tsx
> +        keyExtractor={(item, index) => `${index}`}
Tror ikke keys bør defineres basert på index, kanskje den heller skulle vært en concat av `item.type` og `item.id`?

2021-09-01 12:46 UTC, cbrevik commented on src/screens/Ticketing/Purchase/Payment/SelectCreditCard/index.tsx
> +        text="Til betaling"
Burde komme fra translations

2021-09-02 09:20 UTC, brorhb commented on src/screens/Ticketing/Purchase/Payment/SelectCreditCard/index.tsx
> +        keyExtractor={(item, index) => `${index}`}
Lurt, gjorde det et annet sted, så gir mening å gjøre det her også 😊

2021-09-08 08:59 UTC, rosvik approved these changes
Bare noe småpirk fra meg. Ser bra ut 👍

2021-09-08 11:43 UTC, brorhb commented on src/screens/Ticketing/Purchase/Confirmation/index.tsx
> +                  //await fetchPaymentOptions();
Takk! Hang igjen fra tidligere forsøk :smile:

2021-09-08 13:04 UTC, cbrevik requested changes
Noen småting og best practices (altså litt nitpick), men også noen ting som burde rettes opp i `number` vs `string` på response fra API. Tror vi er ganske nærme en merge her nå!

2021-09-08 13:04 UTC, cbrevik commented on src/screens/Ticketing/Purchase/Confirmation/index.tsx
> +                      }}
Her bør det brukes `type="body__primary--bold"` i stedet for å eksplisitt sette fontWeight eller fontSize

2021-09-08 13:04 UTC, cbrevik commented on src/screens/Ticketing/Purchase/Confirmation/index.tsx
> +                }}
Unngå inline styles

2021-09-08 13:04 UTC, cbrevik commented on src/screens/Ticketing/Purchase/Confirmation/index.tsx
> +                    }}
Unngå inline styles

2021-09-08 13:04 UTC, cbrevik commented on src/screens/Ticketing/Purchase/Payment/SelectPaymentMethod/index.tsx
> +          }}
Bruk `type="heading__title"` i stedet for sette font-style direkte

2021-09-08 13:04 UTC, cbrevik commented on src/screens/Ticketing/Purchase/Payment/SelectPaymentMethod/index.tsx
> +        }}
inline

2021-09-09 06:36 UTC, cbrevik approved these changes
Superduper! 🥇 Dette ble veldig bra @brorhb, og kjapt implementert! Blir artig å tilby dette i appen, det har vært veldig etterspurt.

2021-09-09 06:40 UTC, merged