Providing saving of payment cards to signed in users
AtB-AS/mittatb-app pull request #1568
Opened 2021-09-10 07:28 UTC by brorhb

2021-09-14 12:35 UTC, cbrevik requested changes
Jeg tror fortsatt vi bør tillate folk å kjapt gjenbruke forrige valgt alternativ selv om de ikke er logget inn

2021-09-14 12:35 UTC, cbrevik commented on src/screens/Ticketing/Purchase/Confirmation/index.tsx
> +            previousMethod?.paymentType === PaymentType.Vipps ? (
Blir dette rett? Lagring av forrige brukte metode lokalt i appen er ikke det samme som å lagre kortet på brukeren?

2021-09-15 10:37 UTC, brorhb commented on src/screens/Ticketing/Purchase/Confirmation/index.tsx
> +            previousMethod?.paymentType === PaymentType.Vipps ? (
Hensikten her er at vi alltid lagrer previous hvis brukeren betalte med Vipps, slik at kunden kan rask bruke vipps igjen neste gang en billett skal kjøpes 😊 Men vi kan sikkert lagre unna om de ønsker å betale med Visa/MC også, slik at det går raskere å gjøre det også?

2021-09-16 07:02 UTC, cbrevik approved these changes
Ser bra ut! Bare to småting

2021-09-16 08:38 UTC, merged