build: add firebase app distribution android staging
AtB-AS/mittatb-app pull request #1599
Opened 2021-09-23 08:55 UTC by mortlun

2021-09-23 11:37 UTC, gorandalum commented
Kunne du skrevet litt om hva hensikten til endringen er? Det er jo ikke lenket til noen issue som har noe informasjon. Det er sikkert etablert mellom deg og Christian nå, men kjekt å få noe formulert skriftlig i tilfelle man i fremtiden inspiserer endringene og lurer på hva årsaken var.

2021-09-24 09:12 UTC, cbrevik requested changes
Det eneste som endrer seg her ser ut til å være at du base64-encoder keystore og distribusjonskanal?

Jeg tror heller vi bør få til "matrix" med en `atb` og en `nfk` matrix, hvor distribusjonskanal og hvilke env variabler som brukes er det som endres for hver matrix: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix

Altså at de eksisterende workflowene endres for å muliggjøre det, og ikke at vi legger til en ny

2021-09-29 08:50 UTC, mortlun commented
> Det eneste som endrer seg her ser ut til å være at du base64-encoder keystore og distribusjonskanal?
> 
> Jeg tror heller vi bør få til "matrix" med en `atb` og en `nfk` matrix, hvor distribusjonskanal og hvilke env variabler som brukes er det som endres for hver matrix: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
> 
> Altså at de eksisterende workflowene endres for å muliggjøre det, og ikke at vi legger til en ny
> 
> Samt at keystore encryptes på samme vis, skjønner at du ikke var fornøyd med det, men vi trenger ikke enda en måte å gjøre det samme på 😅

Enig at det hadde vært nice å brukt samme flow, men det er en endring der - "Distribute to Firebase app distribution". Vet ikke om steg er konfigurerbart.

2021-09-29 08:55 UTC, mortlun commented
> Kunne du skrevet litt om hva hensikten til endringen er? Det er jo ikke lenket til noen issue som har noe informasjon. Det er sikkert etablert mellom deg og Christian nå, men kjekt å få noe formulert skriftlig i tilfelle man i fremtiden inspiserer endringene og lurer på hva årsaken var.

Lagt til en liten beskrivelse

2021-09-29 09:51 UTC, cbrevik commented
>Enig at det hadde vært nice å brukt samme flow, men det er en endring der - "Distribute to Firebase app distribution". Vet ikke om steg er konfigurerbart.

Joda, det er bare å legge inn en conditional. `if: matrix.org == 'nfk'`. Tilsvarende for `atb` med vårt steg. Eller så kan vi rewrite fastlane-filen til å håndtere spesifikk deploy, basert på `APP_ORG` (kanskje mer ryddig også).

2021-11-18 08:34 UTC, mikaelbr reviewed
Jeg har ikke brukt environment i GH tidligere, og syns dette ble overraskende rent. Så for meg først en veldig manuell prosess for håndtering av envvars via strategy matrix, men å kombinere strategy med env fungerte jo ypperlig!

2021-11-18 12:01 UTC, cbrevik commented
Ah så de har enabled environments for vanlig repos også nå, skal se over igjen litt senere

2021-11-18 12:04 UTC, cbrevik commented on .github/workflows/build-staging-android.yml
> +          echo $KEYSTORE | base64 -di > android/app/keystore.jks
Har ikke fått sett ordentlig over enda, men er denne testa? `i`-argumentet betyr vel "input file"? Her kommer input fra stdin?

2021-11-18 12:05 UTC, cbrevik commented on .github/workflows/build-staging-android.yml
> +          echo $KEYSTORE | base64 -di > android/app/keystore.jks
Kan dette også flyttes til scriptet? Altså `create-keystore-file.sh`, så kan det brukes på tvers av workflows

2021-11-23 13:36 UTC, cbrevik approved these changes
Ser greit ut dette 👍🏻

2021-11-23 13:39 UTC, cbrevik commented
Vi må vurdere om det samme skal gjøres med iOS eller ei, bygget der kan fort bli en time langt. Timeout på 90 minutter vil slukes opp fort

2021-11-24 09:39 UTC, merged