feat: show travel card in ticketing
AtB-AS/mittatb-app pull request #1654
Opened 2021-10-12 12:49 UTC by rosvik

Legger til visning av t:kort på under Billetter, og deaktiverer kontroll på mobil av aktive billetter.

![collage](https://user-images.githubusercontent.com/1774972/137298615-db371c24-5d88-4820-b39a-52810f1f3e79.png)

- Flytter også meldingsboksen på toppen av kjøpefanen inn i scrollview, slik at den ikke tar for mye plass.

## TODO:

- [x] Oversettelser (egen issue AtB-AS/kundevendt#449)
- [x] UU testing
- [x] Vis i billetkontroll-knapp og bottom sheet?
- [ ] Linke til nettbutikk for å endre t:kort?

### Oversettelser:

```js
ticketInfo: {
  tCardIsActive: _(
    'T:kort er satt som reisebevis',
    'T:card is set as travel document',
  ),
  noInspectionIcon: _('Ikke bruk\ni kontroll', 'Not for\ninspection'),
},
travelCardInformation: {
  reisebevis: _('Reisebevis', 'Travel document'),
  onInspection: _(
    'I billettkontroll må du vise t:kortet ditt:',
    'In the event of an inspection, you need to show your t:card:',
  ),
  changeInstructions: _(
    'Kan endres fra Mitt AtB',
    'Can be changed in My AtB',
  ),
  tCard: _('t:kort', 't:card'),
},
```

resolves AtB-AS/kundevendt#1613

2021-10-14 10:17 UTC, cbrevik commented on src/tickets/TicketContext.tsx
> +          // },
Tror du fint an legge til Bugsnag.notity-delen her ja

2021-10-14 10:22 UTC, cbrevik requested changes
![image](https://user-images.githubusercontent.com/4932625/137299503-f8b48541-9731-4a42-831b-fb2845015c9e.png)
Fikk en feil når jeg logget ut, kanskje relatert til at dokumentet er tomt i Firestore?

2021-10-14 10:22 UTC, cbrevik commented on src/screens/Ticketing/Tickets/TravelCardInformation.tsx
> +      </ThemeText>
Tror denne teksten må kommenteres bort, det er ikke mulig enda :D

2021-10-14 10:30 UTC, rosvik commented on src/screens/Ticketing/Tickets/TravelCardInformation.tsx
> +      </ThemeText>
Bør det heller stå link til nettbutikk? Eller er det bedre å fjerne hele teksten?

2021-10-14 10:48 UTC, cbrevik commented
Tror vi trenger litt margin under "Du har ingen aktive billetter". 
![image](https://user-images.githubusercontent.com/4932625/137303227-60c1061d-4bf8-4391-ac8b-6326b3a43417.png)

2021-10-14 10:48 UTC, cbrevik commented on src/screens/Ticketing/Tickets/TravelCardInformation.tsx
> +      </ThemeText>
Hm tror vi kan leve uten, men kan ta opp det på mandag med Hilde

2021-10-14 11:14 UTC, rosvik commented on src/tickets/TicketContext.tsx
> +          // },
Noe sånt? be4a5ac66337b25c2a2a49f9f7e7624f88dee37a

2021-10-14 13:53 UTC, merged

2021-10-15 06:27 UTC, tormoseng commented on src/screens/Ticketing/Tickets/TicketsScrollView.tsx
> +    ? isFuture(travelCard?.expires.toDate())
Vi har ikke håndtering for å varsle bruker etc om dette i nettbutikken. Det som nå skjer er vel at validator gir rødt, kunden spør oss/kundesenter om hvorfor, og må bytte t:kort. Vet ikke om vi trenger å forholde oss til det her i appen nå. Men et godt spørsmål.