wip: add "Mitt reisebevis" screen
AtB-AS/mittatb-app pull request #2151
Opened 2022-02-11 11:49 UTC by gorandalum

2022-02-14 12:31 UTC, cbrevik requested changes

2022-02-14 12:31 UTC, cbrevik commented on src/mobile-token/MobileTokenContext.tsx
> +      .then(setTravelTokens);
Burde kanskje funksjonen som brukes i `useCallback` her være async slik som `toggleTravelToken` lengre ned, med `try`/`catch` i tillegg?

2022-02-25 13:47 UTC, gorandalum commented on src/mobile-token/MobileTokenContext.tsx
> +      .then(setTravelTokens);
Jeg tror det blir mye støy siden kallet går fast hvert kvarter. Dette er jo et http-kall, så får error-logging fra client uansett.

2022-02-27 19:15 UTC, merged

2022-03-14 08:13 UTC, tormoseng commented
Denne saken er isolert sett OK. Testes også som del av helheten rundt "token toggle".