feat: add train notice on period tickets
AtB-AS/mittatb-app pull request #2232
Opened 2022-03-01 13:25 UTC by rosvik

Legger til melding om samarbeidsbilletten også for periodebilletter. 

Også en fiks av at meldingsboksen forsvinner utenfor skjemen når der ikke er nok plass. Litt usikker på om å legge til en tom `FullscreenFooter` er beste måten å gjøre det på, men det ser ut til å fungere greit.

closes #2155

2022-03-01 20:12 UTC, gorandalum requested changes

2022-03-01 20:12 UTC, gorandalum commented on src/screens/Ticketing/Ticket/Details/DetailsScreen.tsx
> +        </FullScreenFooter>
Synes det blir litt vel hackish. Kunne man heller prøvd en `marginBottom` på `MessageBox`?

2022-03-02 09:53 UTC, rosvik commented on src/screens/Ticketing/Ticket/Details/DetailsScreen.tsx
> +        </FullScreenFooter>
Fant kilden til problemet her! Hele ScrollView-et ble feil høyde, siden padding var lagt inn som `style` ikke `contentContainerStyle`. Oppdatert i f4f1f3195dc0f62b3f4fa5480965d260e13f4384

2022-03-03 08:55 UTC, rosvik commented
Oppdatert med fiks av at melding vises under "utløpte billetter". Nå vises den kun hvis billetten er gyldig.

2022-03-03 13:43 UTC, gorandalum approved these changes

2022-03-03 13:50 UTC, merged