fix: update travel-token-box title styling
AtB-AS/mittatb-app pull request #2237
Opened 2022-03-01 14:55 UTC by rosvik

Oppdatert styling på tittel i travel-token-box. Ref. [slack-tråd](https://mittatb.slack.com/archives/C0116FMPX4Y/p1646134161002599)

![Simulator Screen Shot - iPhone 13 - 2022-03-01 at 15 53 15](https://user-images.githubusercontent.com/1774972/156191578-ed1a9974-def8-4703-b0f4-501a6e4b8041.png)

2022-03-01 20:08 UTC, gorandalum requested changes

2022-03-01 20:08 UTC, gorandalum commented on src/travel-token-box/index.tsx
> +  },
Generelt er det litt fy-fy og overstyre typografien manuelt, den skal komme fra designsystemet. 
Her er typografien i Figma: https://www.figma.com/file/3rlcixpbhfBglNSctUkMys/?node-id=22%3A150
Typografien skal kunne spesifiseres med `type`-parameteren på `ThemeText`.

2022-03-02 09:27 UTC, rosvik commented on src/travel-token-box/index.tsx
> +  },
Ser at jeg kan sette type til default og så gjennomsiktighet til 0.6, så får vi i det minste `fontWeight` fra design-systemet. Er det bedre? Alternativet er det vel å oppdatere design-systemet med en gjennomsiktig tekst, men er det litt overkill?

2022-03-02 11:00 UTC, rosvik commented on src/travel-token-box/index.tsx
> +  },
La inn forslag her: 4aea83dbf1880d4c9a13d9e6683bd623cbf7fc33

2022-03-03 11:59 UTC, gorandalum approved these changes

2022-03-03 12:31 UTC, merged