feat: removes logo from header and adds service disruptions, adding reset search to tabpress
AtB-AS/mittatb-app pull request #2375
Opened 2022-03-21 12:41 UTC by mikaelbr

Removes all logo from header on all screens and sub screens.
Adds service disruption icon to assistant and departures view
adds service disruption url to remote config.
Adds service disruption bottom sheet to navigate to page
Since we remove the reset view option this is moved to tab bar on tab press when scrolled to top (fixes #2201 )
Improves some stability and rerender performance for resetview and helper functions

Closes #2290.

---

Some comments
- primary_2 as logo icon is hardcoded now, as it was previously. Haven't investigated if this can be improved. 

 

TODO
- [x] Update e2e tests
- [x] Handle press when not in focus.
- [x] Set focus on service disruption message on open

---

Demo:

https://user-images.githubusercontent.com/606374/159262855-eef3cb64-397c-44da-9aa6-d05cde2b35a7.mov

Reset view:

https://user-images.githubusercontent.com/606374/159432820-2b75c82f-1a97-451a-a45a-91e07ee234ac.mov

Other screenshots and examples:

<details>

![Screenshot 2022-03-21 at 13 39 15](https://user-images.githubusercontent.com/606374/159262916-375f1b0e-3f63-47ae-b5da-eed9cc390c8c.png)
![Screenshot 2022-03-21 at 13 39 09](https://user-images.githubusercontent.com/606374/159262923-eb1c0ec6-9fed-42b3-9673-2d4fbe8458a0.png)
![Screenshot 2022-03-21 at 13 38 34](https://user-images.githubusercontent.com/606374/159262925-b79c7b8a-89ec-46a2-94ea-dbf7e36fbb1a.png)
![Screenshot 2022-03-21 at 13 38 25](https://user-images.githubusercontent.com/606374/159262929-e7f45ce4-2889-4b15-bde5-69db6b18b2d9.png)
![Screenshot 2022-03-21 at 13 38 17](https://user-images.githubusercontent.com/606374/159262933-6cc63ae5-79c6-4f5a-b548-42580a792977.png)
![Screenshot 2022-03-21 at 13 38 10](https://user-images.githubusercontent.com/606374/159262940-612c6dc6-0315-487b-8281-707c83d58bfa.png)

</details>

2022-03-22 13:51 UTC, tormoseng commented
Fikset opp i e2e-testene, inkludert å fjerne reisesøk for v1 som er borte i 1.18. Spesifikke tester for denne saken tas i #2384

2022-03-22 14:30 UTC, mikaelbr commented
@hildeor og @strombraaten Kan være kjekt om dere ser videoer her så kan vi ta 5 min til å demoe løsning om om det er behov for det.

2022-03-22 14:38 UTC, rosvik approved these changes
LGTM 👍

2022-03-22 14:38 UTC, rosvik commented on src/translations/components/ServiceDisruptions.ts
> +    'Get an overview of changes, delays and service disruptions at atb.no (Norwegian only):      ',
Litt vel mye whitespace her?

```suggestion
    'Get an overview of changes, delays and service disruptions at atb.no (Norwegian only):',
```

2022-03-22 14:38 UTC, rosvik commented on src/translations/components/ServiceDisruptions.ts
> +      'atb.no/driftsavvik (åpnes i nettleser)      ',
```suggestion
      'atb.no/driftsavvik (åpnes i nettleser)',
```

2022-03-22 14:46 UTC, strombraaten commented on src/translations/components/ServiceDisruptions.ts
> +    'Get an overview of changes, delays and service disruptions at atb.no (Norwegian only):      ',
![image](https://user-images.githubusercontent.com/72508979/159508938-77f147ad-3f83-4480-98cc-cd1a92edff18.png)

2022-03-22 14:47 UTC, mikaelbr commented on src/translations/components/ServiceDisruptions.ts
> +      'atb.no/driftsavvik (åpnes i nettleser)      ',
Ajaj, bra. Copypaste + formatering der altså

2022-03-22 14:52 UTC, strombraaten commented
> @hildeor og @strombraaten Kan være kjekt om dere ser videoer her så kan vi ta 5 min til å demoe løsning om om det er behov for det.

@mikaelbr Ser i utgangspunktet bra ut det her, men må du virkelig holde inne i ett sekund for å nullstille reisesøket? For deeet virker rart sånn brukeropplevelsemessig. Er det noen måte vi kan jobbe vårs rundt det på sånn at man bare kan tæppe som vanlig?

2022-03-22 15:10 UTC, mikaelbr commented
Oh. Det minner meg på en ting. må adressere longpress når man er på andre views. Skriver TODO

2022-03-22 15:19 UTC, tormoseng commented
Ikke testet selv, men fungerer likt på Android?

2022-03-22 15:21 UTC, mikaelbr commented
Ja skal ikke være noe forskjell på det. Jeg er ikke umiddelbart kjent med om det er vanlig praksis.

2022-03-22 15:30 UTC, strombraaten commented
> Nei ikke et sekund, men lengre enn et "vanlig tap". Dette kalles "long press" på iOS og det er liksom det som har erstattet f.eks 3d-press osv. Det føles forholdsvis naturlig på telefonen og det gir en fordel over press for scroll til topp + press for reset i den form av at du kan gjøre det når som helst (selv om du er scrollet ned).

Vi kan plukke opp tråden igjen når du er tilbake i neste uke 👌 Er ikke dønn i mot longpress nødvendigvis, men om det er et alternativ så vil jeg jo si at virker som et mer etablert pattern å kun tæppe som du ville gjort ellers.

2022-03-22 16:40 UTC, mikaelbr commented on src/service-disruptions/ServiceDisruptionSheet.tsx
> +const ServiceDisruptionSheet = forwardRef<ScrollView, Props>(
Takk! Var usikker på hva som var hensikten med den!

2022-03-22 16:43 UTC, mikaelbr commented
> Er ikke dønn i mot longpress nødvendigvis, men om det er et alternativ så vil jeg jo si at virker som et mer etablert pattern å kun tæppe som du ville gjort ellers.

Dette følger verktøyet vi bruker direkte, så det var en kortere og mer stabil veg til målet. Jeg slet litt i starten med å finne en naturlig måte å fortsatt ivareta scroll på (altså press + press), men etter å ha reflektert litt utover dagen nå så tror jeg at jeg har en måte å løse det på. Men jeg er ikke umiddelbart sikker på hva som er beste brukermønster her da. Kunne vært interessant om vi hadde sett litt på andre apps og hva de gjør (både på android og ios).

2022-03-24 08:03 UTC, monopoint commented
jeg stiller meg litt skeptisk til long press.
det betyr vel at vi får en knapp med to funksjoner der den ene funksjoner er "hemmelig" og krever opplæring.
Det blir også mer kompleksitet for skjermleser, der brukeren må ta et valg når denne knappen har fokus ("double tap to navigate or double tap and hold to reset search") Ironisk nok blir det her en bedre brukeropplevelse for UU enn for vanlige :sweat_smile: 

Det er en back listener på Android i dette viewet, som resetter søket på tilbakeklikk i denne situasjonen. Husk å test den.

2022-03-24 09:03 UTC, tormoseng commented
@mikaelbr En heads-up. Fjernet e2e for reisesøk i https://github.com/AtB-AS/mittatb-app/pull/2390. Dvs, samme endringer som i commit https://github.com/AtB-AS/mittatb-app/pull/2375/commits/b31817f578a2fe336de362234155113a22cfff44

2022-03-24 09:24 UTC, monopoint commented
trykk på service Disruptions-knappen gir dette:
![image](https://user-images.githubusercontent.com/1464594/159884805-6d8894dd-eb6c-4288-a821-cb7b3fc82bcc.png)

2022-03-24 09:42 UTC, monopoint requested changes
fant noen mangler under testing. se tidligere kommentar

2022-03-24 09:52 UTC, mikaelbr commented
Det kan implementeres med tap om er scrollet i toppen. Instagram og twitter har forøvrig longpress på bytte av profiler

2022-03-24 11:19 UTC, gorandalum commented on src/service-disruptions/ServiceDisruptionSheet.tsx
> +          <View ref={focusRef}>
Jeg så Espen meldte om en feil på dette. Det demrer noe i hodet mitt om at det på Android må være gitt `accessible={true}` på View` for at fokus skal fungere.

2022-03-24 11:38 UTC, monopoint commented
>  ..Forsida blir vel det som Espen refererer som `current location`, ikke sant?
med `current location` så mener jeg GPS-posisjon. når vi nullstiller søket skal vi bruke GPS-posisjon i `From`-feltet, ikke tomt felt

2022-03-24 11:59 UTC, gorandalum commented
> når vi nullstiller søket skal vi bruke GPS-posisjon i `From`-feltet, ikke tomt felt

Hvis brukeren har delt GPS-posisjonen sin. Hvis ikke så er det tomt.

2022-03-24 12:14 UTC, monopoint commented
> > når vi nullstiller søket skal vi bruke GPS-posisjon i `From`-feltet, ikke tomt felt
> 
> Hvis brukeren har delt GPS-posisjonen sin. Hvis ikke så er det tomt.

ja, det er riktig presisering. I testen jeg gjorde ble altså from-feltet satt tomt, selv om jeg har GPS-posisjonering på

2022-03-25 11:55 UTC, hildeor commented
> Det kan implementeres med tap om er scrollet i toppen. Instagram og twitter har forøvrig longpress på bytte av profiler

Instagram har også enkelt-tapping som en tilbake-knapp, som jeg tenker er mest nærliggende å sammenligne med. 
Long press for å bytte profil gir sånn sett mening da man bytter en kontekst, mens for nullstilling av reisesøk syns jeg det ligner mest på "ta meg tilbake til utgangspunktet".

2022-03-28 05:53 UTC, mikaelbr commented
Her er det engasjement!

> Long press på Assistant-knappen resetter from og to-feltene til tomme felt, men ønsket oppførsel er vel at from resettes til Current location

Observert en bug med dette fra reset view. Urelatert til dette, men kan se på det samtidig som koden er oppe.

> Er det noen "tekniske konflikter" da egentlig?

Nei, ikke annet enn at jeg var på konferanse.

> Jeg testet backhandleren i Android nå, og den funket ikke, men, den funker heller ikke i 1.16.

Så så vidt på dette før jeg dro men ikke gjort implementasjon. Så du løste det i egen sak. Flott!

2022-03-28 07:48 UTC, mikaelbr commented
> Long press på Assistant-knappen resetter from og to-feltene til tomme felt, men ønsket oppførsel er vel at from resettes til Current location

Litt heisenberg-bug her visst. Får ikke reprodusert per nå. Jeg har gjort noe generell stabilitetsforbedringer som en konsekvens av noe annet, men får ikke reprodusert så usikker på om det er fordi det er fikset eller for at det ikke er enkelt å reprodusere.

2022-03-28 07:52 UTC, mikaelbr commented on src/components/disappearing-header/index.tsx
> +  tabPressBehaviour?: {
Denne er gruppert inn for mer korrekt typedefinisjon uten for avanserte union types. Konsekvens er at man må være litt mer nøye i hook dependency checks som er lengre ned her.

2022-03-28 07:53 UTC, mikaelbr commented on src/components/disappearing-header/index.tsx
> +    scrollYValue,
Bruker ref her for å unngå ny subscriber for hver scroll men fortsatt ha gjeldende korrekt scroll data.

2022-03-28 07:55 UTC, mikaelbr commented on src/translations/dictionary.ts
> +      `Aktiver for reisesøk, trykk to ganger for å nullstille søket.`,
Usikker på om dette fanger opp nyansene godt nok, men tror ikke vi skal være for verbos på en sa hyppig lest knapp heller.

2022-03-28 07:55 UTC, mikaelbr commented on src/translations/dictionary.ts
> +      `Aktiver for reisesøk, trykk to ganger for å nullstille søket.`,
Kanskje det burde være 
```suggestion
      `Aktiver for reisesøk. Aktiver to ganger for å nullstille søket.`,
```

2022-03-28 07:55 UTC, mikaelbr commented on src/translations/dictionary.ts
> +      'Activate for search assistant, press twice to reset search.',
Samme da her:
```suggestion
      'Activate for search assistant. Activate twice to reset search.',
```

2022-03-28 07:55 UTC, mikaelbr commented on src/translations/dictionary.ts
> +      'Activate for search assistant, press twice to reset search.',
cc @strombraaten

2022-03-28 08:55 UTC, strombraaten commented on src/translations/dictionary.ts
> +      'Activate for search assistant, press twice to reset search.',
@mikaelbr Med på den 👍

2022-03-29 10:32 UTC, gorandalum approved these changes

2022-03-29 10:38 UTC, merged