feat: Firestore-basert konfigurering av tilbakemeldingskomponent
AtB-AS/mittatb-app pull request #2377
Opened 2022-03-21 14:46 UTC by toretefre

Har lagt til:

- dismissable
- surveyVersion

Mangler:

- alwaysShow
- gracePeriodDisplayCount
- repromptDisplayCount

2022-03-28 11:02 UTC, toretefre commented
Når denne merges må `feedbackQuestions`-collection og Firestore-rules kopieres over fra staging til prod. Kan være greit å avvente til vi får oppdaterte språk-formuleringer.

2022-03-28 19:15 UTC, gorandalum requested changes
Hei. Det ser i hovedsak bra ut, men jeg tror det er noen forenklinger som kan gjøres. I tillegg er det noen småting som bryter litt med tidligere praksis i dette prosjektet. Det er litt vanskelig å kommentere på det, så jeg tenker vi kan prøve å ta en runde parprogrammering på det så raskt som mulig. Kanskje i morgen?

2022-03-31 13:53 UTC, toretefre commented
Da skal denne være klar. Har ikke funnet noe som avviker fra våre brukerhistorier under testing. 

Etter reprompt blir komponenten nå vist helt til spørsmålet blir besvart eller brukeren klikker på "ikke still dette spørsmålet igjen", slik at brukeren ikke går glipp av sjansen til å gi feedback etter å ha blitt kjent med funksjonaliteten. 

Remote config kommer på et senere punkt.

2022-04-04 16:06 UTC, toretefre commented
Inkluderte inn en fix på #2419 her. Skal prøve å få testet den når jeg får satt opp VoiceOver, og kommentere her når det eventuelt har blitt gjort.

2022-04-04 20:09 UTC, gorandalum approved these changes
Ser bra ut. Husk å vent med merge til etter 1.17 er releaset.

2022-04-20 09:13 UTC, merged