fix: filter fareproducts by distribution channel
AtB-AS/mittatb-app pull request #2518
Opened 2022-04-19 10:24 UTC by monopoint

2022-04-19 10:47 UTC, gorandalum requested changes
Tror dette er løst på feil plass, denne logikken må nok implementeres nærmere selve kjøpsflyten. Feltet `distributionChannel` handler om hvilken kanal produktet skal selges i, men det må kunne vises frem likevel. Tenk på klippekort som er kjøpt i nettbutikk: Det skal ikke kunne selges i app, men skal likevel kunne vises frem i app.

2022-04-19 12:41 UTC, gorandalum approved these changes
LGTM :+1:

2022-04-19 12:41 UTC, gorandalum commented on __tests__/utils-test.ts
> +        return product.distributionChannel.some((channel) => channel === 'web');
Navngiving `defaultsHaveAppChannel` matcher ikke med logikken `channel === 'web'`.

2022-04-20 06:40 UTC, monopoint commented on __tests__/utils-test.ts
> +        return product.distributionChannel.some((channel) => channel === 'web');
@gorandalum @jorelosorio 
The first part of the test merely checks if there are any web distribution channels at all in the data set (expect true). The second part of the test uses the actual predicate we are testing.

2022-04-20 06:46 UTC, monopoint commented on __tests__/utils-test.ts
> +        return product.distributionChannel.some((channel) => channel === 'web');
ah, :palm_tree: 
gotcha. the name of the variable.

2022-04-20 11:00 UTC, merged