feat: modernise generic onboarding
AtB-AS/mittatb-app pull request #2813
Opened 2022-07-12 11:24 UTC by Nisha1306

Solves https://github.com/AtB-AS/kundevendt/issues/1916 
Figma Link: https://www.figma.com/file/zdZwvobgpEWSagKt0tderx/App-1.2?node-id=5222%3A21656

It has been discussed with @cbrevik to not upgrade the illustrations.

2022-07-13 10:37 UTC, monopoint commented
Wrong color in status bar (android)
![image](https://user-images.githubusercontent.com/1464594/178714539-30748d1d-670b-48af-899e-76d10237c728.png)

2022-07-13 11:05 UTC, monopoint requested changes
some feedback

2022-07-13 11:05 UTC, monopoint commented on src/screens/Onboarding/index.tsx
> +      <Tab.Navigator
add
```
<StatusBar
    backgroundColor={theme.static.background[themeColor].background}
/>
```
for android

2022-07-14 07:23 UTC, Nisha1306 commented on src/screens/Onboarding/index.tsx
> +        <Tab.Screen name="IntercomInfo" component={IntercomInfo} />
We are not really sure about this. This task was to make the look and feel of general onboarding to be in sync with Mobile token onboarding. So not sure why we have the fourth screen is here. Also we do not have any onboarding for testpilot like the second screen, so we have ignored that as well. Have also discussed with @cbrevik  and concluded on adding the location screen separately if its needed.  Issue added https://github.com/AtB-AS/kundevendt/issues/2031

2022-07-14 08:59 UTC, monopoint approved these changes
:+1:

2022-07-14 09:21 UTC, merged