fix: Removed left padding on error message box in trip search
AtB-AS/mittatb-app pull request #3342
Opened 2023-03-03 13:36 UTC by hanne-at-atb

Closes: https://github.com/AtB-AS/kundevendt/issues/3579

2023-03-03 14:13 UTC, ingvisim requested changes
This seems to remove the padding on other containers on the trip search page. Might have to create a new style for the message box with only bottom padding

2023-03-06 09:02 UTC, jorelosorio commented on src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/components/Results.tsx
> -      <View style={styles.container}>
Looks good however `styles.container` was only used here, so it might not be in use by other components.

2023-03-06 09:12 UTC, jorelosorio approved these changes

2023-03-06 09:14 UTC, ingvisim approved these changes

2023-03-06 10:17 UTC, merged