fix: Change letter spacing to avoid line break
AtB-AS/mittatb-app pull request #3368
Opened 2023-03-09 13:48 UTC by ingvisim

![Screenshot_1678369631](https://user-images.githubusercontent.com/85479566/224044808-d9ef03d3-807a-410d-bceb-9e8959bb6535.png)

2023-03-09 14:01 UTC, rosvik commented
For context: Seems like some letter spacing values sometimes creates line break issues on some Android devices. Exactly which values creates issues seems arbitrary, so this PR updates it to a value that appear to create fewer issues. The issue was noticed on a Pixel 6 Pro, which works as expected now.

(https://github.com/facebook/react-native/issues/35039)

2023-03-09 14:30 UTC, gorandalum requested changes
I think I would rather prefer a fix in `ThemeText` for this. Change the letter spacing if the device is Pixel 6 Pro (or a Pixel, or an Android, we decide how wide we want to target this fix).

2023-03-10 12:37 UTC, gorandalum approved these changes

2023-03-10 12:45 UTC, merged

2023-03-14 08:27 UTC, HanneLH commented
Tested ok på Android og iOS ✅