fix: correct colors on line
AtB-AS/mittatb-app pull request #3523
Opened 2023-05-05 10:42 UTC by adriawh

2023-05-08 08:17 UTC, rosvik approved these changes

2023-05-08 09:18 UTC, gorandalum requested changes
I think there is something wrong with the `Section`/`LocationInputSectionItem` if these styles are necessary. I would first look into why it is actually behaving this way, and not giving the "normal" delimiter color.

2023-05-12 09:20 UTC, adriawh commented
@oyvindmikkelsenatb

2023-05-24 07:31 UTC, gorandalum approved these changes

2023-05-24 09:22 UTC, merged