fix: wrong expiry date shown on payment card
AtB-AS/mittatb-app pull request #3524
Opened 2023-05-05 13:58 UTC by adriawh

When a cards shown expire date on the card is shown as 01.2024, it is valid thru the entire month of January and the expire date is technically 02.2024. The latter is how It is stored in the app currently, which I would say is the correct way to store the expire date. Therefore a simple fix is to do as I have done here, subtract one month when getting the string to show.

2023-05-08 09:57 UTC, rosvik approved these changes

2023-05-08 11:50 UTC, gorandalum reviewed
This will work both for winter and summer time?

2023-05-12 07:45 UTC, adriawh commented
> This will work both for winter and summer time?

I belive so. The expiry date will always be stored the same, one month ahead, and since the method is not using hours for any calculations it should. 

I also tried testing by setting the date to January and it seems to work correctly.

2023-05-12 10:42 UTC, gorandalum requested changes
I have thought about this a little, and since the timestamp is exactly at midnight between two months, I think it is safer to subtract one day than one month.

2023-05-12 11:30 UTC, gorandalum approved these changes

2023-05-12 11:45 UTC, merged