fix: prevent crash on websocket connection
AtB-AS/mittatb-app pull request #3536
Opened 2023-05-10 12:34 UTC by rosvik

Related to feedback from testing of https://github.com/AtB-AS/kundevendt/issues/3418

Handles the different states of a websocket connection, and returns the subscription only when it is open. _Should_ prevent the app from crashing on slower iOS devices.

Also logs the status to Bugsnag if it doesn't follow the happy path.

2023-05-10 13:38 UTC, gorandalum requested changes
- Even though the web socket is only used one place, I feel it can be refactored into it's own hook like `useWebSocket`.
- Could using the methods `onopen`, `onclose` and `onerror` remove the need for these "manual retries" and tracking the retry cound?
- Think a little about naming, the web socket changes name between `ws`, `openConnection` and `subscription` throughout the implementation, which makes it a little more confusing than it needs to be.

2023-05-12 14:34 UTC, rosvik commented
@gorandalum Re-did pretty much the entire implementation 😅 Decided to add a `useSubscription`, and named everything outside of it `subscription`, while the implementation uses `WebSocket`. Hopefully that makes more sense.

2023-05-16 08:38 UTC, gorandalum commented
> @gorandalum Re-did pretty much the entire implementation 😅 Decided to add a `useSubscription`, and named everything outside of it `subscription`, while the implementation uses `WebSocket`. Hopefully that makes more sense.

I think it looks much better :+1:

2023-05-16 08:38 UTC, gorandalum approved these changes

2023-05-16 11:53 UTC, merged