fix: accessibility improvements ticket assistant
AtB-AS/mittatb-app pull request #3888
Opened 2023-09-22 09:23 UTC by adriawh

### PR targeting these comments:
 [Comment](https://github.com/AtB-AS/kundevendt/issues/4240#issuecomment-1727277990)
>Comments form testing.
Should the "header" billettveileder be in the app, is missing now compared with figma sketches.
Missing a space between dot and next sentence.
Is it a reason for both Back and close bottoms?
200% zoom the part with "hvor ofte" and "hvor lenge" gets ugly on 200% text size, for the numbers and calender.

 [Additional comment on screen reader focus](https://github.com/AtB-AS/kundevendt/issues/4240#issuecomment-1727465075). 
 >Skjermeleser kommentar.
Det har vært optimalt at fokuset til skjermleseren går opp til overskriften når man går til neste siden, nå er det litt bingo i hva som skjer når man kommer til neste side. En gang går den til overskriften, en gang er den nede neste knappen.

Regarding this comment:
> Is it a reason for both Back and close bottoms?

This was added after a decision from @Sebstorvik and marked.

Changes: 
- Added header
- Fix for 200% zoom
- Fixed space after dot in child ticket
- With screen reader, focus now on header after navigating

2023-09-22 11:45 UTC, marius-at-atb requested changes
Nice! Some initial comments

2023-09-22 11:45 UTC, marius-at-atb commented on src/stacks-hierarchy/Root_TicketAssistantStack/use-naviagtion-focus.ts
> +      navigation.getState().routeNames[navigation.getState().index] ==
Whether the array lookup is a safe operation depends on the navigation state.
I'm not sure if it is always valid, and would add a safety check just for peace of mind ;)

2023-09-22 11:45 UTC, marius-at-atb commented on src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_CategoryPickerScreen.tsx
> +                  key={index}
key should probably be `u.id`

2023-09-22 13:45 UTC, jorelosorio commented on src/stacks-hierarchy/Root_TicketAssistantStack/TicketAssistant_CategoryPickerScreen.tsx
> +import {TICKET_ASSISTANT_CATEGORY_PICKER_SCREEN} from '@atb/stacks-hierarchy/Root_TicketAssistantStack/Root_TicketAssistantStack';
We use this kind of upper-cased words for constant, not sure if this is the case.

2023-09-22 14:08 UTC, jorelosorio approved these changes
Looks good.

2023-09-25 08:07 UTC, gorandalum requested changes

2023-09-25 08:07 UTC, gorandalum commented on src/stacks-hierarchy/Root_TicketAssistantStack/use-navigation-focus.ts
Could you write some about why this `useNavigationFocus` is needed, and what differs it from `useFocusOnLoad`? In general it is not beneficial for the app to have similar hooks that does almost the same thing. Maybe it can instead be a param to `useFocusOnLoad`?

2023-09-26 11:35 UTC, marius-at-atb reviewed
Some details and a topic of discussion regarding the hook

2023-09-26 11:35 UTC, marius-at-atb commented on src/stacks-hierarchy/Root_TicketAssistantStack/use-navigation-focus.ts
Regarding `useFocusOnLoad`, maybe we should use `useFocusEffect` instead?
https://reactnavigation.org/docs/use-focus-effect/#how-is-usefocuseffect-different-from-adding-a-listener-for-focus-event

As `useFocusOnLoad` is currently implemented, `giveFocus` is triggered when `focusRef` is set, without checking if the component is part of a page that is in focus. So e.g. if a component is created in the DOM, but is part of a different tab than the one in focus, it will still trigger `giveFocus` (unless manually updating and overriding with `setFocusOnLoad`).

However if we skip `useFocusEffect`, and instead update `useFocusOnLoad` with a param as suggested by @gorandalum, then I guess that integration can also fix the issue I just described at the same time.

2023-10-03 11:13 UTC, marius-at-atb approved these changes
Very nice!

2023-10-10 08:17 UTC, gorandalum approved these changes

2023-10-10 08:20 UTC, merged