fix: travel search cleanup and animation
AtB-AS/mittatb-app pull request #3892
Opened 2023-09-22 13:51 UTC by adriawh

### Changes:
- Moved favorites on the same line as location and map buttons
- Only show search results when typing
- Animation between states
- Added delay to info box so it appear for split second while searching
- Removed debounce on first letter, to make results start appearing quicker
- Moved info box within scrollview to simplify logic

Video:
https://github.com/AtB-AS/mittatb-app/assets/70323886/f30a134e-cdfc-4d13-a354-2599be9afac6

2023-09-25 08:00 UTC, gorandalum requested changes
I think this solution may be too complex for what it is trying to solve. It introduces animations, timeouts, listening to chip layout changes, and some more. I know it might be necessary to introduce those complexities to fully implement the design as described, but we should take a foot in the ground and think if it is really worth it. From experience we know animations is hard to both write and read, and also they can be buggy and brittle.

My first test would be how will it look without any custom animations. If we instead simply just not render the chip-components when the user starts typing, in combination with adding the `animateNextChange`. I would like to see a video of how that looks :)

2023-09-26 11:57 UTC, marius-at-atb commented
Even though animations can be brittle and introduce more complexity, I think it is a challenge we should accept.
The best apps tend to be very good at subtle animations that produce a super fluent feel.

2023-09-26 12:13 UTC, adriawh commented
@marius-at-atb 

Were able to create animations with a  "cheaper" method, and also simplified the logic in my latest changes

2023-09-26 12:36 UTC, gorandalum approved these changes
Looks good!

2023-09-26 12:55 UTC, marius-at-atb approved these changes
I like it!
Bonus point if you can get the travel search results section above the buttons:
![Simulator Screenshot - iPhone 14 - 2023-09-26 at 14 47 52](https://github.com/AtB-AS/mittatb-app/assets/134292729/07bcb55f-640d-450a-8fdf-2d42d7c45ff0)

2023-09-26 12:55 UTC, marius-at-atb commented on src/favorites/FavoriteChips.tsx
> +          style,
If adding style anyway, there is no need for the conditional check above. Or did you mean to remove line 59?

2023-09-28 06:04 UTC, merged