Adriawh/no acces to location departures
AtB-AS/mittatb-app pull request #3983
Opened 2023-10-26 06:28 UTC by adriawh

2023-11-02 13:58 UTC, marius-at-atb requested changes
Nice!
Just need to make sure that selecting a favorite location still works when no location permission granted.

2023-11-02 13:58 UTC, marius-at-atb commented on src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx
> +      {hasLocationPermission ? (
```suggestion
      {hasLocationPermission || !!location ? (
```
Also check if a location has been selected from favorites

2023-11-02 13:58 UTC, marius-at-atb commented on src/translations/screens/Nearby.ts
> +      'Holdeplassar i nærleiken er ikkje tilgjengelege.',
```suggestion
      'Haldeplassar i nærleiken er ikkje tilgjengeleg.',
```

2023-11-02 13:58 UTC, marius-at-atb commented on src/translations/screens/Nearby.ts
> +      title: _('Del din posisjon', 'Share your position', 'Del din posisjon'),
```suggestion
      title: _('Del din posisjon', 'Share your position', 'Del posisjonen din'),
```

2023-11-02 14:00 UTC, marius-at-atb commented on src/nearby-stop-places/NearbyStopPlacesScreenComponent.tsx
> +      {hasLocationPermission ? (
Flipping the condition could also be an option:
`{!hasLocationPermission ? <EmptyState ... /> : <StopPlaces ... />`

2023-11-03 09:16 UTC, gorandalum requested changes
Passing around React-components not as children are not really good practice, as it breaks the out-of-the-box shadow dom optimisations of React.

In addition the button inside the `EmptyState` component is probably ment to be styled in a certain way, and by opening up for passing in any button the component looses the ability to control its own design. I'm guessing we would never want a full width primary button in the `EmptyState` component.

The fix here is to change the input fields of the `EmptyState` component to be text strings and the onpress function, while creating the `Button` component and controlling the style of it is done inside the `EmptyState` component.

2023-11-03 12:13 UTC, marius-at-atb approved these changes
:+1:

2023-11-07 07:35 UTC, gorandalum approved these changes

2023-11-10 07:09 UTC, merged