feat: Add a confirmation screen
AtB-AS/mittatb-app pull request #4237
Opened 2024-01-17 07:03 UTC by jorelosorio

Closes https://github.com/AtB-AS/kundevendt/issues/16030

2024-01-18 14:25 UTC, marius-at-atb approved these changes
Nice and clean! 🧹 

Something to think about when using this, is the transition in and out. I'm guessing a fade transition would be good.

2024-01-19 08:14 UTC, jorelosorio commented
> Nice and clean! 🧹
> 
> Something to think about when using this, is the transition in and out. I'm guessing a fade transition would be good.

For now, I think it takes the default one.

2024-01-19 12:59 UTC, gorandalum requested changes
GW! Looks pretty clean :+1: Some comments on some subtle improvements that can be made, but the one regarding function as screen params should at least be looked on 😊

2024-01-19 12:59 UTC, gorandalum commented on src/stacks-hierarchy/Root_ConfirmationScreen.tsx
> +        <ThemeIcon size="large" svg={ConfirmSvg} fill={themeColor.text} />
Should not use `fill` parameter, that is for overriding with colors outside of the design system. Try using `colorType` instead.

2024-01-19 14:16 UTC, jorelosorio commented on src/stacks-hierarchy/navigation-types.ts
> +  onCompleted: () => void;
Fixed.

2024-01-19 14:16 UTC, jorelosorio commented on src/stacks-hierarchy/Root_ConfirmationScreen.tsx
> +        <ThemeIcon size="large" svg={ConfirmSvg} fill={themeColor.text} />
Fixed

2024-01-22 12:48 UTC, gorandalum approved these changes

2024-01-22 12:48 UTC, gorandalum commented on src/utils/use-complete-onboarding-and-enter-app.ts
> +
Could we move this to stacks-hierarchy/navigation-types? It is now used in a non-onboarding-context.

2024-01-22 12:48 UTC, gorandalum commented on src/stacks-hierarchy/navigation-types.ts
> +  nextScreen: NextScreenParams<'Root_TabNavigatorStack'>;
Do you need the generics here anymore with the updated typing for `NextScreenParams`?

2024-01-22 14:44 UTC, jorelosorio commented on src/stacks-hierarchy/Root_ConfirmationScreen.tsx
> +      () => navigation.navigate(nextScreen.screen, nextScreen.params),
By removing the generic as mentioned here: https://github.com/AtB-AS/mittatb-app/pull/4237/files#r1461808581 the compiler complains:

![image](https://github.com/AtB-AS/mittatb-app/assets/43450882/381cd0b3-1ea5-4733-8928-965f1f61a66d)

2024-01-23 09:00 UTC, jorelosorio commented on src/stacks-hierarchy/Root_ConfirmationScreen.tsx
> +      () => navigation.navigate(nextScreen.screen, nextScreen.params),
I leave the generic set in order to avoid this issue, lets have a look when implementing.

2024-01-23 09:07 UTC, merged