fix: update Norwegian translation for FRAM
AtB-AS/mittatb-app pull request #4402
Opened 2024-03-21 07:52 UTC by mortennordseth

Change the translation of "See live" from "Se live" to "Se direkte" to improve clarity for Norwegian users for FRAM. 

Fixes https://github.com/AtB-AS/kundevendt/issues/17346

2024-03-21 11:21 UTC, reidzeibel approved these changes

2024-03-21 11:25 UTC, gorandalum requested changes
Jeg synes dette blir alt for spesifikk greie til å ha overstyring på. Det blir en slippery-slope hvis vi går denne veien hvor man overstyrer helt vanlige tekster i app. Det skal jo ikke være så stor forskjell på brukerne i Møre og Trøndelag at man behøver forskjellige fraseringer.

Når det er sagt, så betyr ikke det at dere nødvendigvis ikke skal få til at teksten blir "Se direkte" i app. Hvis dere mener at den teksten er bedre for brukerne i Møre så kommer den nok til å være bedre for brukerne i Trøndelag også. Men ta en runde med designerne og bli enige om hvilken tekst vi skal ha.

2024-04-19 11:54 UTC, rosvik approved these changes
Looks good 👍

2024-04-19 13:50 UTC, gorandalum approved these changes

2024-04-22 06:40 UTC, merged