fix: avoid ambiguous messages about whether correspondence can or cannot be guaranteed
AtB-AS/mittatb-app pull request #4427
Opened 2024-04-11 11:31 UTC by jonasbrunvoll

Closes

### What is wrong, and what is expected behavior?

A user has asked us a question regarding ambiguous messages. The messages at the top of the app say that correspondence cannot be guaranteed, while the message a little further down says that there is correspondence between 340 and 341 (picture 1). This is confusing. 

### Proposed solution
Remove the last sentence "Kan ikke garantere korrespondanse.", if the message box "Korrespondanse mellom 340 og 341 på Volda sjukehus" appears.   

### Illustration Solution
<details>
<Summary>screenshots/video</Summary>

![Image](https://github.com/AtB-AS/kundevendt/assets/59939294/2955fa05-a7e1-4297-8501-6e8b23ef10be)

![Image](https://github.com/AtB-AS/kundevendt/assets/59939294/da398c48-a5b1-4549-8c7e-37084141e14d)

</details>

2024-04-11 12:18 UTC, gorandalum requested changes
This is ment to be handled by `shortWaitTimeAndNotGuaranteedCorrespondence`. Could you look into why that isn't working instead? I think it has something to do with the intermediate walking leg between the corresponding departures.

2024-04-11 13:10 UTC, jonasbrunvoll commented
> This is ment to be handled by `shortWaitTimeAndNotGuaranteedCorrespondence`. Could you look into why that isn't working instead? I think it has something to do with the intermediate walking leg between the corresponding departures.

Yes,  as I have understood the problem, `timeIsShort` inside the function `shortWaitTimeAndNotGuaranteedCorrespondence` returns true beacuse the waiting time between bus changes is too short. This makes the sentance "Kan ikke garantere korrespondanse." being included, although the correspondence is guaranteed.

2024-04-15 12:46 UTC, closed without merging

2024-04-15 12:47 UTC, gorandalum requested changes

2024-04-15 12:47 UTC, gorandalum commented on src/travel-details-screens/utils.ts
> +  if (hasGuaranteedCorrespondence(legs)) return false;
If there is a non-corresponding short wait time between two legs of the trip, then this method should return `true`. I think this now may be masked by some other corresponding legs, which overrides the answer to `false`.