feat: extend the travel mode filter selection to set filter using the selected_as_default property
AtB-AS/mittatb-app pull request #4486
Opened 2024-05-07 12:16 UTC by jonasbrunvoll

Closes https://github.com/AtB-AS/kundevendt/issues/17913

 ### Background

FRAM and NFK have requested that some transport mode filters should be unchecked by default in both app and travel planner web. This request highlights a need that we need to address. As the number of organizations in the OMS grows, it becomes increasingly more difficult to find on singel transport mode configuration that will work well for all orgnaizations. Therefore, each organization should be able to configure their own desired default transportModes. 

The requests from AtB, FRAM and NFK are as following:
-  **AtB:** All transport mode filters should be checked by default (7/7).
-  **NFK:** All transport mode filters except flight should be check by default (6/7).
-  **FRAM:** All transport mode filters except flight and train should be checked by default (5/7).

#### Illustrations
<details>
<summary>screenshots/video/figma</summary>

https://github.com/AtB-AS/mittatb-app/assets/59939294/cd3b3b78-e2db-4b83-9f7b-d61173237c5a

</details>

### Proposed solution
- [x] Use the property `selectedAsDefault` to determine whether a transport mode filters should be checked or unchecked by default. 
- [x] Display a message box informing the users about how many of the filters are checked, if any other combination but the default filters are checked. 
- [x] Reset to default filters when the box with filter information is crossed away. 

### Acceptence criteria 
- [ ] The correct transport mode filters are checked by default.
- [ ] The user is still able to specify which transport mode filters to use during the search.

2024-05-10 08:02 UTC, gorandalum requested changes
In my testing the green dot logic didn't work as described in the user-stories. On a fresh install there was a green dot on the filters button if not every transport mode was selected as default.

Also there needs to be some description of backwards compatibility things to test, to be sure it works well with filters the user has previously stored.

Note that acceptance criteria and test input should be described on the issue/PR that is in the board. Since this PR is not in the board, it should be described on the connected issue.

2024-05-13 06:13 UTC, jonasbrunvoll commented
> In my testing the green dot logic didn't work as described in the user-stories. On a fresh install there was a green dot on the filters button if not every transport mode was selected as default.
> 
> Also there needs to be some description of backwards compatibility things to test, to be sure it works well with filters the user has previously stored.
> 
> Note that acceptance criteria and test input should be described on the issue/PR that is in the board. Since this PR is not in the board, it should be described on the connected issue.

A blunder on my part to forget the logic of the green dot. Will fix it now

2024-05-14 07:37 UTC, gorandalum approved these changes
Good work! Some minor comments that can be taken a look at before merging :)

2024-05-14 07:37 UTC, gorandalum commented on src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/__tests__/are_non_default_filters_selected.test.ts
Remove 'non' from the file name? As the function is named `areDefaultFiltersSelected`.

2024-05-14 07:37 UTC, gorandalum commented on src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/__tests__/are_non_default_filters_selected.test.ts
> +  });
Could also add a test for empty array.

2024-05-14 07:37 UTC, gorandalum commented on src/stacks-hierarchy/Root_TabNavigatorStack/TabNav_DashboardStack/Dashboard_TripSearchScreen/utils.ts
> +  return !transportModes.some((tm) => tm.selectedAsDefault !== tm.selected);
I think `transportModes.every((tm) => tm.selectedAsDefault === tm.selected)` is quite a bit easier to read than using `some` which needs two negations in the statement. And I think they should end up the same 😅 At least we have some tests to check it.

2024-05-14 08:42 UTC, merged