chore: remove metro warning for non-serializable values on navigation
AtB-AS/mittatb-app pull request #4494
Opened 2024-05-10 09:22 UTC by reidzeibel

Not related to any issues.

This PR will remove the console warning when you select "Log in" from profile screen, the warning is: 

`Non-serializable values were found in the navigation state`

I removed the `transitionPreset` from navigation call and the warning no longer shows, and tested on both simulator and emulator, the animation still works fine.

2024-05-13 07:14 UTC, gorandalum requested changes
I was probably a little unclear in the comment that caused this PR. I didn't mean that all `transitionPreset` applied in the app was redundant and could be removed, I ment that the underlying issue of warnings in the console when applying the should be removed.

One possible way to do that might be to change the type from `TransitionPreset` to something like `'slideUp' | 'slideFromRight'`, and map those values to an actual `TransitionPreset` when using them in the options.

2024-05-13 07:15 UTC, gorandalum commented
> I was probably a little unclear in the comment that caused the latest changes. I didn't mean that all `transitionPreset` applied in the app was redundant and could be removed, I ment that the underlying issue of warnings in the console when setting `transitionPreset` should be removed.
> 
> One possible way to do that might be to change the type from `TransitionPreset` to something like `'slideUp' | 'slideFromRight'`, and map those values to an actual `TransitionPreset` when using them in the options.

2024-05-13 07:17 UTC, reidzeibel commented
Oooh, got it, thanks for the pointers!

2024-05-15 04:56 UTC, reidzeibel commented
closing this for the time being to focus on the 1.51 release

2024-05-15 04:56 UTC, closed without merging