feat: Global message to inform about flexible tickets for anonymous
AtB-AS/mittatb-app pull request #4644
Opened 2024-07-31 10:25 UTC by jorelosorio

Closes https://github.com/AtB-AS/kundevendt/issues/18591

![Simulator Screenshot - iPhone 15 - 2024-07-31 at 12 15 18](https://github.com/user-attachments/assets/a1a113e7-80a6-4160-917f-df6d3ce47d15)

2024-07-31 16:21 UTC, reidzeibel commented on src/global-messages/types.ts
> +  appAnonymousFlexibleTickets = 'app-anonymous-flexible-tickets',
I think this should be `appTicketingAnonymous` to be consistent with how we name the global message context. From my understanding, the global message can be used on various cases, not only flexible ticket.

2024-08-01 08:50 UTC, gorandalum requested changes
Could you elaborate some on why we need a new global message context? We already have a global message context on the same place in the app.

2024-08-01 09:15 UTC, jorelosorio commented
> Could you elaborate some on why we need a new global message context? We already have a global message context on the same place in the app.

I do not have an explanation, of why. However, I see that there was a previous global message with different rules validations and context than the one we want to show here. So then I put another one with different rules.

Existing:
```ts
<GlobalMessage
                globalMessageContext={
                  GlobalMessageContextEnum.appPurchaseOverview
                }
                textColor="background_0"
                ruleVariables={{
                  preassignedFareProductType: preassignedFareProduct.type,
                  fromTariffZone: fromPlace.id,
                  toTariffZone: toPlace.id,
                }}
              />
```

Added one:

```ts
              <GlobalMessage
                globalMessageContext={
                  GlobalMessageContextEnum.appAnonymousFlexibleTickets
                }
                textColor="background_0"
                ruleVariables={{
                  isLoggedIn: isLoggedIn,
                }}
              />
```

Any better suggestion?

2024-08-01 09:18 UTC, gorandalum commented
What about adding the rule variable `isLoggedIn` to the existing context?

2024-08-01 11:22 UTC, gorandalum commented
I took a closer look at this in the code and what we have before. Can we use the global rule variable `authenticationType` for this? 🤔

2024-08-01 11:25 UTC, jorelosorio commented
> I took a closer look at this in the code and what we have before. Can we use the global rule variable `authenticationType` for this? 🤔

`isLoggedIn` is basically a `authenticationType == 'phone'`, so we can switch to `authenticationType` if it wants a more detailed rule.

2024-08-01 11:27 UTC, gorandalum commented
But isn't `authenticationType` already there, so we might not need any code changes?

2024-08-01 11:32 UTC, jorelosorio commented
> But isn't `authenticationType` already there, so we might not need any code changes?

No, the code as is right now, does not have any rule for `authenticationType`. I see is inside a conditional, `isFree` but that one does not depend on the user login state.

2024-08-01 14:08 UTC, gorandalum commented
> No, the code as is right now, does not have any rule for `authenticationType`. I see is inside a conditional, `isFree` but that one does not depend on the user login state.

Seems like it is there as a global rule variable, applicable to all rules:
https://github.com/AtB-AS/mittatb-app/blob/9c6e29ad013ba95253cacb51cbc25994a3745f2d/src/global-messages/GlobalMessage.tsx#L45

2024-08-02 07:45 UTC, jorelosorio commented
We found a global variable definition for all rules that includes authenticationType, so this PR is being closed.

![image](https://github.com/user-attachments/assets/8d8511dd-9581-4fe2-9266-7fc002354fe8)

2024-08-02 13:37 UTC, gorandalum reviewed
And have you tested it with a rule in global messages? I'm a little concerned regarding the `userTypeString` list not being filtered 🤔

2024-08-02 13:50 UTC, jorelosorio commented
> And have you tested it with a rule in global messages? I'm a little concerned regarding the `userTypeString` list not being filtered 🤔

Yes, it loosk like:

<img width="590" alt="image" src="https://github.com/user-attachments/assets/338b82b1-0878-4fc5-b726-210ea53bdc02">

2024-08-02 14:21 UTC, jorelosorio commented
> > And have you tested it with a rule in global messages? I'm a little concerned regarding the `userTypeString` list not being filtered 🤔
> 
> Yes, it loosk like:
> 
> <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/43450882/354616801-338b82b1-0878-4fc5-b726-210ea53bdc02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDgzNjMsIm5iZiI6MTcyMjYwODA2MywicGF0aCI6Ii80MzQ1MDg4Mi8zNTQ2MTY4MDEtMzM4YjgyYjEtMDg3OC00ZmM1LWI3MjYtMjEwZWE1M2JkYzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE0MTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZDQ3YzBhMzhlNjk0ZDU5ZWExN2ZiYTMzMzBiMWQxZDAzZWExYTdlODY2YjQzNjgyMzMxYjljMTNhOGYxNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UjYYIf7gfpzdM9vZFzn9HGCtl8vroOjYkyyMk19z6Vw">

I also added a new rule called `onlyContains` if we want to make sure only that element appears. @gorandalum

2024-08-02 14:31 UTC, gorandalum commented
> > And have you tested it with a rule in global messages? I'm a little concerned regarding the `userTypeString` list not being filtered 🤔
> 
> Yes, it loosk like:
> 
> <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/43450882/354616801-338b82b1-0878-4fc5-b726-210ea53bdc02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDkyNjIsIm5iZiI6MTcyMjYwODk2MiwicGF0aCI6Ii80MzQ1MDg4Mi8zNTQ2MTY4MDEtMzM4YjgyYjEtMDg3OC00ZmM1LWI3MjYtMjEwZWE1M2JkYzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE0MjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZGRlNWI2NTRjZWViNzIzYjg3M2UxOGZkNTg1ZGRhNzg2YTRmN2RkODc5NTEyNWM4ZTBiZDk5Y2FmZmQxZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fCc-7axR1iPVM1_R71cT5ZsiEugfhIIplCb0BPyXtOs">

Doesn't seem to work as intended for me, here the global message comes even though I haven't selected adult as traveller. Think it needs some filtering.
<img width=400 src="https://github.com/user-attachments/assets/1c10ce6a-e547-415a-85b6-52cd4e715868"/>

2024-08-04 08:30 UTC, jorelosorio commented
> > > And have you tested it with a rule in global messages? I'm a little concerned regarding the `userTypeString` list not being filtered 🤔
> > 
> > 
> > Yes, it loosk like:
> > <img alt="image" width="590" src="https://private-user-images.githubusercontent.com/43450882/354616801-338b82b1-0878-4fc5-b726-210ea53bdc02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MDkyNjIsIm5iZiI6MTcyMjYwODk2MiwicGF0aCI6Ii80MzQ1MDg4Mi8zNTQ2MTY4MDEtMzM4YjgyYjEtMDg3OC00ZmM1LWI3MjYtMjEwZWE1M2JkYzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDE0MjkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkZGRlNWI2NTRjZWViNzIzYjg3M2UxOGZkNTg1ZGRhNzg2YTRmN2RkODc5NTEyNWM4ZTBiZDk5Y2FmZmQxZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fCc-7axR1iPVM1_R71cT5ZsiEugfhIIplCb0BPyXtOs">
> 
> Doesn't seem to work as intended for me, here the global message comes even though I haven't selected adult as traveller. Think it needs some filtering. <img alt="" width="400" src="https://private-user-images.githubusercontent.com/675421/354628933-1c10ce6a-e547-415a-85b6-52cd4e715868.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NjAzODQsIm5iZiI6MTcyMjc2MDA4NCwicGF0aCI6Ii82NzU0MjEvMzU0NjI4OTMzLTFjMTBjZTZhLWU1NDctNDE1YS04NWI2LTUyY2Q0ZTcxNTg2OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQwODI4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNmRkN2MxOGEyODk0ZDYwMzE5OWRlNGEwNjE3N2UxNTlkYTg5YzA0Y2I0M2JiNjhlMDhiYzdlYzcxYTEyMDJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZMCMPtNVANrsGHEbpc1BNDfV9nlgIuOE_oMiL8ZtgQ0">

Use the new rule, contains Only instead.

2024-08-05 07:11 UTC, gorandalum approved these changes
Good. Remember to update the acceptance criteria so they actually target the two new features:
- Possibility to use the `userTypes` rule in the `appPurchaseOverview` context.
- Possibility to use the new rule operator `onlyContains` on all rules where the variable is a list.

2024-08-05 07:22 UTC, merged