feat: Add expand property to the button
AtB-AS/mittatb-app pull request #4883
Opened 2024-12-16 07:16 UTC by jorelosorio

Part of: https://github.com/AtB-AS/kundevendt/issues/17880

<img width="393" alt="image" src="https://github.com/user-attachments/assets/2383cf46-0c86-4232-afdf-f3003e1a1ae0" />

2024-12-16 09:23 UTC, jorelosorio commented
> The change it self look ok, but some more surrounding work needs to be done:
> 
> * It need to be aligned with [Figma](https://www.figma.com/design/2QTjAdekdIPuLFovQhVrY3/Components?node-id=9051-96246&t=KcKIQjG8GdXsLNYL-4), both with regards to look, icon placement and parameter name.
> * This change makes it not necessary to have the large and medium buttons, as the only difference between them are the width.

Hi, I will contact design to align the Figma, At the last meeting they agreed to do those changes, and I am going to follow up.

2024-12-16 13:12 UTC, jorelosorio commented
@ckbilstad and I had a meeting about the button and we agreed on removing the large button and keep small and large, so for both cases, the expand prop can be used, however, for the small the icon and text will be centred. I might take more effort to remove the medium button usage.

2024-12-18 10:02 UTC, gorandalum requested changes
Regarding the `expand` field, should it be `expanded` to follow the convention from the other fields?

I tested this branch out locally, and a couple things stood out:
- Icons on large expanded buttons aren't placed correctly.
- Large buttons in the app are no longer expanded.

Screenshots:
<div>
<img width=350 src="https://github.com/user-attachments/assets/736fd413-cd84-4e34-830a-e9f9d795c25b" />
<img width=350 src="https://github.com/user-attachments/assets/7c218b22-fbe7-4175-9f41-7a71978319ba" />
</div>

2025-01-06 12:45 UTC, jorelosorio commented
I made fixes for this PR @gorandalum

2025-01-07 07:11 UTC, jorelosorio commented
The implementation of this expand button in this PR was not working properly and was moved out to a new PR https://github.com/AtB-AS/mittatb-app/pull/4907

2025-01-07 07:11 UTC, closed without merging